[project]
name = "ladybugtools_toolkit"
readme = "README.md"
authors = [
    { name = "BHoM", email = "bhombot@burohappold.com" }
]
dynamic = ["version", "description"]
dependencies = [
    "case-converter",
    "dataframe-image",
    "matplotlib",
    "meteostat",
    "numpy",
    "openpyxl",
    "pandas",
    "pyarrow",
    "pyet",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "pytest-order",
    "scikit-learn",
    "scipy",
    "tables",
    "tqdm",
    "xlrd","attrs",
    "Brotli",
    "click",
    "click-plugins",
    "colorama",
    "contourpy",
    "cycler",
    "dragonfly-comparison",
    "dragonfly-core",
    "dragonfly-display",
    "dragonfly-doe2",
    "dragonfly-energy",
    "dragonfly-radiance",
    "dragonfly-schema",
    "dragonfly-uwg",
    "fonttools",
    "honeybee-core",
    "honeybee-display",
    "honeybee-doe2",
    "honeybee-energy",
    "honeybee-energy-standards",
    "honeybee-idaice",
    "honeybee-ies",
    "honeybee-openstudio",
    "honeybee-radiance",
    "honeybee-radiance-command",
    "honeybee-radiance-folder",
    "honeybee-radiance-postprocess",
    "honeybee-schema",
    "honeybee-standards",
    "inflate64",
    "jsonschema",
    "jsonschema-specifications",
    "kiwisolver",
    "ladybug-comfort",
    "ladybug-core",
    "ladybug-display",
    "ladybug-display-schema",
    "ladybug-geometry",
    "ladybug-geometry-polyskel",
    "ladybug-radiance",
    "ladybug-rhino",
    "ladybug-vtk",
    "lbt-dragonfly==0.12.99",
    "lbt-honeybee==0.9.95",
    "lbt-ladybug==0.27.150",
    "lbt-recipes==0.26.23",
    "lockfile",
    "luigi",
    "matplotlib",
    "multivolumefile",
    "numpy",
    "openstudio",
    "packaging",
    "pillow",
    "pollination-handlers",
    "psutil",
    "py7zr",
    "pybcj",
    "pycryptodomex",
    "pydantic==1.10.22",
    "pydantic-openapi-helper==0.2.11",
    "pyparsing",
    "pyppmd",
    "python-daemon",
    "python-dateutil",
    "PyYAML",
    "pyzstd",
    "queenbee",
    "queenbee-local",
    "referencing",
    "rpds-py",
    "six",
    "tenacity",
    "texttable",
    "tornado",
    "typing_extensions",
    "uwg",
    "vtk",
]

[urls]
source = "https://github.com/BHoM/LadybugTools_Toolkit"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "black",
    "ipykernel>=6.29.5",
    "pylint>=3.3.5",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "pytest-order",
    "sphinx>=8.1.3",
    "sphinx-bootstrap-theme>=0.8.1",
    "sphinxcontrib-fulltoc>=1.2.0",
    "sphinxcontrib-napoleon>=0.7",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]

[tool.setuptools.package-data]
"*" = ["*.xlsx", "*.csv", "*.json"]

[tool.pytest.ini_options]
pythonpath = "src"
