
from typing import Dict

from honeybee_energy.material.opaque import (  # EnergyMaterialVegetation,
    EnergyMaterial, _EnergyMaterialOpaqueBase)

# TODO - Add EnergyMaterialVegetation once this material is available via general release.

MATERIALS: Dict[str, _EnergyMaterialOpaqueBase] = {
    "Asphalt": EnergyMaterial(
        identifier="Asphalt",
        roughness="MediumRough",
        thickness=0.2,
        conductivity=0.75,
        density=2360.0,
        specific_heat=920.0,
        thermal_absorptance=0.93,
        solar_absorptance=0.87,
        visible_absorptance=0.87,
    ),
    "ConcreteHeavyweight": EnergyMaterial(
        identifier="ConcreteHeavyweight",
        roughness="MediumRough",
        thickness=0.2,
        conductivity=1.95,
        density=2240.0,
        specific_heat=900.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.8,
        visible_absorptance=0.8,
    ),
    "ConcreteLightweight": EnergyMaterial(
        identifier="ConcreteLightweight",
        roughness="MediumRough",
        thickness=0.1,
        conductivity=0.53,
        density=1280.0,
        specific_heat=840.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.8,
        visible_absorptance=0.8,
    ),
    "DustDry": EnergyMaterial(
        identifier="DustDry",
        roughness="Rough",
        thickness=0.2,
        conductivity=0.5,
        density=1600.0,
        specific_heat=1026.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.7,
        visible_absorptance=0.7,
    ),
    "MetalPainted": EnergyMaterial(
        identifier="MetalPainted",
        roughness="Smooth",
        thickness=0.0015,
        conductivity=5.0,
        density=7690.0,
        specific_heat=410.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.5,
        visible_absorptance=0.5,
    ),
    "MetalReflective": EnergyMaterial(
        identifier="MetalReflective",
        roughness="MediumSmooth",
        thickness=0.0015,
        conductivity=5.0,
        density=7680.0,
        specific_heat=418.0,
        thermal_absorptance=0.75,
        solar_absorptance=0.45,
        visible_absorptance=0.6,
    ),
    "Mud": EnergyMaterial(
        identifier="Mud",
        roughness="MediumRough",
        thickness=0.2,
        conductivity=1.4,
        density=1840.0,
        specific_heat=1480.0,
        thermal_absorptance=0.95,
        solar_absorptance=0.8,
        visible_absorptance=0.8,
    ),
    "Rock": EnergyMaterial(
        identifier="Rock",
        roughness="MediumRough",
        thickness=0.2,
        conductivity=3.0,
        density=2700.0,
        specific_heat=790.0,
        thermal_absorptance=0.96,
        solar_absorptance=0.55,
        visible_absorptance=0.55,
    ),
    "SandDry": EnergyMaterial(
        identifier="SandDry",
        roughness="Rough",
        thickness=0.2,
        conductivity=0.33,
        density=1555.0,
        specific_heat=800.0,
        thermal_absorptance=0.85,
        solar_absorptance=0.65,
        visible_absorptance=0.65,
    ),
    "SoilDamp": EnergyMaterial(
        identifier="SoilDamp",
        roughness="Rough",
        thickness=0.2,
        conductivity=1.0,
        density=1250.0,
        specific_heat=1252.0,
        thermal_absorptance=0.92,
        solar_absorptance=0.75,
        visible_absorptance=0.75,
    ),
    "Softwood": EnergyMaterial(
        identifier="Softwood",
        roughness="MediumSmooth",
        thickness=0.0254,
        conductivity=0.129,
        density=496.0,
        specific_heat=1630.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.65,
        visible_absorptance=0.65,
    ),
    "Hardwood": EnergyMaterial(
        identifier="Hardwood",
        roughness="MediumSmooth",
        thickness=0.0254,
        conductivity=0.167,
        density=680.0,
        specific_heat=1630.0,
        thermal_absorptance=0.9,
        solar_absorptance=0.7,
        visible_absorptance=0.7,
    ),
    "Fabric": EnergyMaterial(
        identifier="Fabric",
        roughness="Smooth",
        thickness=0.002,
        conductivity=0.06,
        density=500.0,
        specific_heat=1800.0,
        thermal_absorptance=0.89,
        solar_absorptance=0.5,
        visible_absorptance=0.5,
    ),
    "Travertine": EnergyMaterial(
        identifier="Travertine",
        roughness="MediumRough",
        thickness=0.2,
        conductivity=3.2,
        density=2700.0,
        specific_heat=790.0,
        thermal_absorptance=0.96,
        solar_absorptance=0.55,
        visible_absorptance=0.55,
    ),
    # "GrassDamp": EnergyMaterialVegetation(
    #     identifier="GrassDamp",
    #     roughness="MediumRough",
    #     thickness=0.1,
    #     conductivity=0.35,
    #     density=1100,
    #     specific_heat=1252,
    #     soil_thermal_absorptance=0.92,
    #     soil_solar_absorptance=0.7,
    #     soil_visible_absorptance=0.7,
    #     plant_height=0.2,
    #     leaf_area_index=1.71,
    #     leaf_reflectivity=0.25,
    #     leaf_emissivity=0.92,
    #     min_stomatal_resist=160,
    # ),
    # "GrassDry": EnergyMaterialVegetation(
    #     identifier="GrassDry",
    #     roughness="Rough",
    #     thickness=0.1,
    #     conductivity=0.3,
    #     density=1100,
    #     specific_heat=1252,
    #     soil_thermal_absorptance=0.89,
    #     soil_solar_absorptance=0.75,
    #     soil_visible_absorptance=0.75,
    #     plant_height=0.2,
    #     leaf_area_index=1.71,
    #     leaf_reflectivity=0.19,
    #     leaf_emissivity=0.95,
    #     min_stomatal_resist=180,
    # ),
    # "SHRUBS": EnergyMaterialVegetation(
    #     identifier="GRASS_DRY",
    #     roughness="Rough",
    #     thickness=0.1,
    #     conductivity=0.35,
    #     density=1260,
    #     specific_heat=1100,
    #     soil_thermal_absorptance=0.9,
    #     soil_solar_absorptance=0.7,
    #     soil_visible_absorptance=0.7,
    #     plant_height=0.2,
    #     leaf_area_index=2.08,
    #     leaf_reflectivity=0.21,
    #     leaf_emissivity=0.95,
    #     min_stomatal_resist=180,
    # ),
}
