using BH.oM.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace BH.oM.LadybugTools
{
    [Description("Command that when executed with the LadybugTools Adapter, runs an External Comfort simulation and returns an ExternalComfort object containing results.")]
    public class RunExternalComfortCommand : ILadybugCommand, IObject
    {
        [Description("A SimulationResult object generated by the RunSimulation Execute command.")]
        public static SimulationResult SimulationResult { get; set; } = null;

        [Description("A Typology object.")]
        public static Typology Typology { get; set; } = null;
    }
}