using BH.oM.Adapter;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace BH.oM.LadybugTools
{
    [Description("Command to use in conjunction with the LadybugToolsAdapter, that simulates a range of angles that a PV panel could rest at, and measures the amount of radiation (and by extension the energy that the panels create) at that angle.")]
    public class SolarPanelTiltOptimisationCommand : ISimulationCommand
    {
        [Description("The EPW file to use for simulation.")]
        public virtual FileSettings EPWFile { get; set; } = new FileSettings();

        [Description("The number of different azimuthal angles to simulate.")]
        public virtual int Azimuths { get; set; } = 3;

        [Description("The number of different altitudinal angles to simulate.")]
        public virtual int Altitudes { get; set; } = 3;

        [Description("The reflectance of the ground.")]
        public virtual double GroundReflectance { get; set; } = 0.2;

        [Description("The irradiance type to plot. Total for all.")]
        public virtual IrradianceType IrradianceType { get; set; } = IrradianceType.Total;

        [Description("Whether to calculate isotropic values during simulation.")]
        public virtual bool Isotropic { get; set; } = true;

        [Description("The analysis period to simulate/plot.")]
        public virtual AnalysisPeriod AnalysisPeriod { get; set; } = new AnalysisPeriod();

        [Description("The title of the plot. Will appear above any information at the top of the plot.")]
        public virtual string Title { get; set; } = "";

        [Description("The location to place any images generated by the command. Leave empty to return a base64 string representation of the image.")]
        public virtual string OutputLocation { get; set; } = "";
    }
}