using BH.oM.Adapter;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace BH.oM.LadybugTools
{
    [Description("Command that when used in conjunction with the LadybugToolsAdapter, will plot a sun path based off of the location data in an EPW file.")]
    public class SunPathPlotCommand : ISimulationCommand
    {
        [Description("The EPW file to use for analysis.")]
        public virtual FileSettings EPWFile { get; set; } = new FileSettings();

        [Description("The analysis period to analyse.")]
        public virtual AnalysisPeriod AnalysisPeriod { get; set; } = new AnalysisPeriod();

        [Description("The size of the sun on the plot.")]
        public virtual double SunSize { get; set; } = 10;

        [Description("The location to place any images generated by the command. Leave empty to return a base64 string representation of the image.")]
        public virtual string OutputLocation { get; set; } = "";
    }
}
