/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2025, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

using BH.oM.Adapter;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace BH.oM.LadybugTools
{
    [Description("Command that when used in conjunction with the LadybugToolsAdapter, will plot a sun path based off of the location data in an EPW file.")]
    public class SunPathPlotCommand : ISimulationCommand
    {
        [Description("The EPW file to use for analysis.")]
        public virtual FileSettings EPWFile { get; set; } = new FileSettings();

        [Description("The analysis period to analyse.")]
        public virtual AnalysisPeriod AnalysisPeriod { get; set; } = new AnalysisPeriod();

        [Description("The size of the sun on the plot.")]
        public virtual double SunSize { get; set; } = 10;

        [Description("The location to place any images generated by the command. Leave empty to return a base64 string representation of the image.")]
        public virtual string OutputLocation { get; set; } = "";
    }
}

